version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chuck-container
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
